{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "flattrack.fullname" . }}-letsencrypt
  labels:
    app.kubernetes.io/part-of: flattrack
    {{- include "flattrack.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.certmanager.email | default "" }}
    privateKeySecretRef:
      name: {{ include "flattrack.fullname" . }}-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
        selector:
          dnsNames:
            {{- range .Values.ingress.hosts }}
            - {{ .host | quote }}
            {{- end }}
{{- end }}
{{- end }}
