apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configuration
  namespace: flattrack-dev
data:
  servers.json: |
    { "Servers": { {
      "Name": "flattrack",
      "Group": "Servers",
      "Host": "postgres",
      "Port": 5432,
      "MaintenanceDB": "FlatTrack",
      "Username": "postgres",
      "SSLMode": "prefer",
      "Comment": "FlatTrack dev database",
      "Password": "postgres",
      "PassFile": "/pgadmin-config/pgpass",
      "SSLCompression": 0,
      "Timeout": 10,
      "UseSSHTunnel": 0,
      "TunnelPort": "22",
      "TunnelAuthentication": 0
     }: "1"}}
  pgpass: |
    postgres:5432:flattrack:postgres:postgres
