apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: flattrack-dev
spec:
  selector:
    io.apisnoop.dba: pgadmin
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  type: NodePort
