stages:
  - lint
  - test
  - build
  - post-build
  - pages

include:
  template: Dependency-Scanning.gitlab-ci.yml

variables:
  ARCH_DEFAULT: "amd64"
  ARCHES: amd64 arm64 arm
  APP_BUILD_VERSION: 0.0.0
  APP_BUILD_MODE: development
  POSTGRES_DB: flattrack
  POSTGRES_USER: flattrack
  POSTGRES_PASSWORD: flattrack
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  IMAGE_GOLANG_ALPINE: docker.io/golang:1.19.3-alpine3.15
  EXTRA_REGISTRIES: docker.io
  IMAGE_GOLANG_ALPINE: docker.io/golang:1.17.0-alpine3.14
  IMAGE_NODE_ALPINE: docker.io/node:15.14.0-alpine3.13
  IMAGE_ALPINE: docker.io/alpine:3.14
  IMAGE_FIRN: registry.gitlab.com/bobymcbobs/container-images/firn:0.0.13-alpha.0
  IMAGE_KO: ghcr.io/google/ko:eb2597f9751c5483baf7ec7f038be9582e5b3a35

.container-registry-login-ko: &container-registry-login-ko |
  ko login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
  ko login "docker.io" -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"

.container-registry-login-crane: &container-registry-login-crane |
  mkdir -p $(getent passwd $(id -u) | cut -d ':' -f6)/.docker
  cat << EOF > $(getent passwd $(id -u) | cut -d ':' -f6)/.docker/config.json
  {
    "auths": {
      "$CI_REGISTRY": {
        "username": "$CI_REGISTRY_USER",
        "password": "$CI_REGISTRY_PASSWORD"
      },
      "https://index.docker.io/v1/": {
        "auth": "$DOCKERHUB_AUTH"
      }
    }
  }
  EOF

.image-build-taggable-name: &image-build-taggable-name |
  set -x
  echo "Commit made on '${CI_COMMIT_TIMESTAMP}'"
  export APP_BUILD_HASH="$CI_COMMIT_SHORT_SHA"
  export APP_BUILD_DATE=$(date --date="${CI_COMMIT_TIMESTAMP//[T+]/ }" '+%Y.%m.%d.%H%M')
  if [[ -z "$CI_COMMIT_TAG" ]]; then
    PRINTABLE_COMMIT_HASH="-$APP_BUILD_HASH"
  fi
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi
  PROJECT_PATH=$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')

.image-pre-build-release-version: &image-pre-build-release-version |
  export APP_BUILD_VERSION=0.0.0
  export APP_BUILD_MODE=production
  export IMAGE_DESTINATIONS="latest$BRANCH_NAME"
  if [[ ! -z "$CI_COMMIT_TAG" ]]; then
    export APP_BUILD_VERSION="$CI_COMMIT_TAG"
    export IMAGE_DESTINATIONS="$APP_BUILD_VERSION"
  fi

.zip-prepare: &zip-prepare |
  export RELEASE_FOLDER_NAME="flattrack$BRANCH_NAME$PRINTABLE_COMMIT_HASH"
  mkdir -p $RELEASE_FOLDER_NAME

build-container:
  stage: build
  image:
    name: $IMAGE_KO
    entrypoint: [""]
  retry: 2
  variables:
    KO_DOCKER_REPO: "$CI_REGISTRY_IMAGE"
  before_script:
    - *container-registry-login-ko
    - *image-build-taggable-name
    - *image-pre-build-release-version
  script:
    - |
      rm -r ./kodata
      mkdir -p ./kodata/{web/dist,}
      cp -r ./migrations ./kodata
      cp -r ./web/dist ./kodata/web
    - |
      ko publish \
      --push \
      --jobs 100 \
      --bare \
      --platform all \
      --tags "${IMAGE_DESTINATIONS}" \
      .
    # TODO use common script - ${CI_PROJECT_DIR}/hack/build-container.sh production
  needs:
    - build-frontend

copy-container-image-to-dockerhub:
  stage: post-build
  image: $IMAGE_GOLANG_ALPINE
  before_script:
    - go install github.com/google/go-containerregistry/cmd/crane@latest
    - *container-registry-login-crane
    - *image-build-taggable-name
    - *image-pre-build-release-version
  script:
    - |
      [ -z "${EXTRA_REGISTRIES}" ] && exit 0
      for TAG in $(echo ${IMAGE_DESTINATIONS:-} | tr ',' ' '); do
        for REG in ${EXTRA_REGISTRIES}; do
          crane copy "${CI_REGISTRY}/${PROJECT_PATH}:${TAG}" "${REG}/${PROJECT_PATH}:${TAG}"
        done
      done

build-helm-chart:
  stage: build
  image: $IMAGE_ALPINE
  variables:
    HELM_LINK: https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
    HELM_HASH: 270acb0f085b72ec28aee894c7443739271758010323d72ced0e92cd2c96ffdb
  allow_failure: true
  before_script:
    - *image-build-taggable-name
    - apk add curl
    - curl -L -o helm.tar.gz $HELM_LINK
    - |
        if [ ! $(sha256sum helm.tar.gz) = $HELM_HASH ]; then
          exit 1
        fi
    - cat helm.tar.gz | tar --directory /usr/local/bin --extract -xz --strip-components 1 linux-amd64/helm
  script:
    - helm package deployments/flattrack --destination .helm-root/helm/
    - helm repo index --url "https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}" .helm-root/
  artifacts:
    paths:
      - .helm-root
  only:
    - master

build-frontend:
  stage: build
  retry: 2
  image: $IMAGE_NODE_ALPINE
  before_script:
    - *image-build-taggable-name
    - *image-pre-build-release-version
    - *zip-prepare
    - cd web
    - apk add --no-cache python2 make g++
    - npm i
  script:
    - npm run build
  after_script:
    - |
      if [[ ! -z "$CI_COMMIT_TAG" ]]; then
        mkdir -p "${RELEASE_FOLDER_NAME}/dist"
        cd web/dist
        cp -R . "${RELEASE_FOLDER_NAME}/dist"
      fi
  artifacts:
    expire_in: 1 day
    paths:
      - web/dist
      - flattrack*/

build-zip-backend:
  stage: build
  retry: 2
  image: $IMAGE_GOLANG_ALPINE
  before_script:
    - *image-build-taggable-name
    - *image-pre-build-release-version
    - *zip-prepare
  script:
    - |
      for ARCH in $ARCHES; do
        echo "Building backend for $ARCH";
        PRINTABLE_ARCH="-$ARCH"
        if [ $ARCH = $ARCH_DEFAULT ]; then
          PRINTABLE_ARCH=
        fi
        CGO_ENABLED=0 GOOS=linux GOARCH="$ARCH" go build \
          -a \
          -installsuffix cgo \
          -ldflags "-extldflags '-static' -s -w \
          -X gitlab.com/flattrack/flattrack/pkg/common.AppBuildVersion=$APP_BUILD_VERSION \
          -X gitlab.com/flattrack/flattrack/pkg/common.AppBuildHash=$APP_BUILD_HASH \
          -X gitlab.com/flattrack/flattrack/pkg/common.AppBuildDate=$APP_BUILD_DATE \
          -X gitlab.com/flattrack/flattrack/pkg/common.AppBuildMode=$APP_BUILD_MODE" \
          -o $RELEASE_FOLDER_NAME/flattrack$PRINTABLE_ARCH \
          main.go
      done
  only:
    - tags
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - flattrack*

build-zip-copy-extras:
  stage: build
  retry: 2
  image: $IMAGE_ALPINE
  before_script:
    - *image-build-taggable-name
    - *image-pre-build-release-version
    - *zip-prepare
  script:
    - cp -r migrations $RELEASE_FOLDER_NAME/migrations
    - cp -r templates $RELEASE_FOLDER_NAME/templates
    - cp example.env $RELEASE_FOLDER_NAME
  only:
    - tags
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - flattrack*

build-zip:
  stage: post-build
  retry: 2
  image: $IMAGE_ALPINE
  needs:
    - build-zip-backend
    - build-zip-copy-extras
  before_script:
    - *image-build-taggable-name
    - *image-pre-build-release-version
    - *zip-prepare
  script:
    - tar cvf $RELEASE_FOLDER_NAME.tar.gz $RELEASE_FOLDER_NAME
  only:
    - tags
    - master
  artifacts:
    paths:
      - flattrack*.tar.gz

test_backend_e2e:
  stage: test
  image: $IMAGE_GOLANG_ALPINE
  variables:
    APP_DB_HOST: postgres
    APP_MINIO_HOST: minio:9000
    APP_MINIO_ACCESS_KEY: minioadmin
    APP_MINIO_SECRET_KEY: minioadmin
    APP_MINIO_BUCKET: flattrack
    APP_MINIO_USE_SSL: "false"
    CGO_ENABLED: "0"
  services:
    - name: postgres:12.2-alpine
      alias: postgres
    - name: minio/minio:RELEASE.2022-01-07T01-53-23Z
      alias: minio
      command:
        - server
        - /data
  before_script:
    - apk add --no-cache git gcc curl
    - go install github.com/onsi/ginkgo/ginkgo@v1.16.4
    - go build -o flattrack main.go
    - ./flattrack &
    - until curl -s http://localhost:8080; do echo "Waiting for API"; sleep 1s; done
  script:
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --progress test/backend/e2e
    - pkill flattrack || true

spell_check:
  stage: lint
  image: $IMAGE_GOLANG_ALPINE
  allow_failure: true
  before_script:
    - go get -u github.com/client9/misspell/cmd/misspell
  script:
    - misspell -error src docs migrations pubic template k8s-manifests README*
    
lint_frontend:
  stage: lint
  image: $IMAGE_NODE_ALPINE
  allow_failure: true
  before_script:
    - cd web
    - apk add --no-cache python2 make
    - npm i
  script:
    - npm run lint

lint_backend:
  stage: lint
  image: $IMAGE_GOLANG_ALPINE
  allow_failure: true
  before_script:
    - apk add git gcc
    - go get -u golang.org/x/lint/golint
  script:
    - echo -e "GOLINT\n"
    - golint -set_exit_status ./...
    - echo -e "GOFMT\n"
    - gofmt -d .

lint_helm_chart:
  stage: lint
  image: $IMAGE_ALPINE
  variables:
    HELM_LINK: https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
    HELM_HASH: 270acb0f085b72ec28aee894c7443739271758010323d72ced0e92cd2c96ffdb
  allow_failure: true
  before_script:
    - apk add curl
    - curl -L -o helm.tar.gz $HELM_LINK
    - |
        if [ ! $(sha256sum helm.tar.gz) = $HELM_HASH ]; then
          exit 1
        fi
    - cat helm.tar.gz | tar --directory /usr/local/bin --extract -xz --strip-components 1 linux-amd64/helm
  script:
    - helm lint deployments/flattrack

pages:
  image:
    # use temporary firn container image instead of theiceshelf/firn image, until tagging is in CI
    name: $IMAGE_FIRN
    entrypoint: [""]
  stage: pages
  before_script:
    - cd docs
  script:
  - firn build
  - mv _firn/_site ../public
  - cp -r ../.helm-root/* ../public
  artifacts:
    paths:
    - public
  only:
    - master
