stages:
  - build

variables:
  ARCH_DEFAULT: "amd64"

build-armv7:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  only:
    - tags
  variables:
    ARCH: "arm/v7"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - set -x
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - |
      mkdir -p $HOME/.docker/cli-plugins
      wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      chmod +x $HOME/.docker/cli-plugins/docker-buildx 
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker buildx create --use --name builder
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      set -x

      APP_BUILD_VERSION=0.0.0
      APP_BUILD_MODE=development

      ARCH_TAGGABLE_NAME="$(echo $ARCH | sed -e 's,/,,g')"
      if [ ! "$ARCH" = "$ARCH_DEFAULT" ]; then
        PRINT_ARCH="-$ARCH_TAGGABLE_NAME"
      fi
      if [ -n "$CI_COMMIT_TAG" ]; then
         APP_BUILD_VERSION="$CI_COMMIT_TAG"
         APP_BUILD_MODE=production
         DOCKER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG$PRINT_ARCH"
      fi
      docker buildx build \
        --build-arg APP_BUILD_VERSION="$APP_BUILD_VERSION" \
        --build-arg APP_BUILD_DATE="$(date -u +%Y-%m-%d_%I:%M:%S%p)" \
        --build-arg APP_BUILD_HASH=$(git rev-parse --short HEAD)" \
        --build-arg APP_BUILD_MODE="$APP_BUILD_MODE" \
        --platform linux/$ARCH \
        -f $CI_PROJECT_DIR/Dockerfile \
        --push \
        -t $CI_REGISTRY_IMAGE:latest$PRINT_ARCH \
        $DOCKER_EXTRA_DESTINATION \
        $CI_PROJECT_DIR

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.13.0
    entrypoint: [""]
  script:
    - |
      sh -c
      APP_BUILD_VERSION="0.0.0";
      APP_BUILD_MODE="development";
      if [ -n "$CI_COMMIT_TAG" ]; then
        APP_BUILD_VERSION="$CI_COMMIT_TAG";
        APP_BUILD_MODE="production";
        KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      fi
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --cache=false \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:latest \
        --build-arg APP_BUILD_VERSION="$APP_BUILD_VERSION" \
        --build-arg APP_BUILD_DATE="$(date -u +%Y-%m-%d_%I:%M:%S%p)" \
        --build-arg APP_BUILD_HASH=$(git rev-parse --short HEAD)" \
        --build-arg APP_BUILD_MODE="$APP_BUILD_MODE" \
        $KANIKO_EXTRA_DESTINATION

