stages:
  - lint
  - test
  - build
  - zip
  - pages

cache:
  key: shared-cache
  paths:
    - .npm
    - /go

variables:
  ARCH_DEFAULT: "amd64"
  ARCHES: amd64 arm64
  APP_BUILD_VERSION: 0.0.0
  APP_BUILD_MODE: development
  POSTGRES_DB: flattrack
  POSTGRES_USER: flattrack
  POSTGRES_PASSWORD: flattrack

.docker-build-pre-script: &docker-build-pre-script |
  set -x
  if ! docker info &>/dev/null; then
    if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
      export DOCKER_HOST='tcp://localhost:2375'
    fi
  fi
  mkdir -p $HOME/.docker/cli-plugins
  wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
  chmod +x $HOME/.docker/cli-plugins/docker-buildx 
  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  docker buildx create --use --name builder
  docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.docker-build-taggable-name: &docker-build-taggable-name |
  apk add git
  set -x
  COMMIT_HASH="???"
  BUILD_DATE="$(date -u +%Y-%m-%d_%I:%M:%S%p)"
  if [[ -z "$CI_COMMIT_TAG" ]]; then
    COMMIT_HASH="$(git rev-parse --short HEAD)"
    PRINTABLE_COMMIT_HASH="-$COMMIT_HASH"
  fi
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi
  ARCH_TAGGABLE_NAME="$(echo $ARCH | sed -e 's,/,,g')"
  if [[ ! "$ARCH" = "$ARCH_DEFAULT" ]]; then
    PRINT_ARCH="-$ARCH_TAGGABLE_NAME"
  fi

.docker-pre-build-release-version: &docker-pre-build-release-version |
  if [[ ! -z "$CI_COMMIT_TAG" ]]; then
    export APP_BUILD_VERSION="$CI_COMMIT_TAG"
    export APP_BUILD_MODE=production
    export DOCKER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE:$APP_BUILD_VERSION$PRINT_ARCH"
  fi

.docker-build: &docker-build |
  docker buildx build --build-arg AppBuildVersion="$APP_BUILD_VERSION" --build-arg AppBuildDate="$BUILD_DATE" --build-arg AppBuildHash="$(git rev-parse --short HEAD)" --build-arg AppBuildMode="$APP_BUILD_MODE" --platform linux/$ARCH -f $CI_PROJECT_DIR/Dockerfile --push -t $CI_REGISTRY_IMAGE:latest$BRANCH_NAME$PRINT_ARCH $DOCKER_EXTRA_DESTINATION $CI_PROJECT_DIR

.zip-prepare: &zip-prepare |
  export RELEASE_FOLDER_NAME="flattrack$BRANCH_NAME$PRINTABLE_COMMIT_HASH"
  mkdir -p $RELEASE_FOLDER_NAME

build-container-amd64:
  stage: build
  image: docker:stable
  retry: 2
  services:
    - docker:stable-dind
  variables:
    ARCH: "amd64"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - *docker-build-pre-script
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
  script:
    - *docker-build

build-container-arm64:
  stage: build
  image: docker:stable
  retry: 2
  services:
    - docker:stable-dind
  variables:
    ARCH: "arm64/v8"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  only:
    - tags
    - master
  before_script:
    - *docker-build-pre-script
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
  script:
    - *docker-build

build-zip-frontend:
  stage: build
  retry: 2
  image: node:14.7.0-alpine3.11
  before_script:
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
    - *zip-prepare
    - npm i
  script:
    - ./node_modules/.bin/vue-cli-service build --dest $RELEASE_FOLDER_NAME/dist src/frontend/main.js
  artifacts:
    expire_in: 20 minutes
    paths:
      - flattrack*

build-zip-backend:
  stage: build
  retry: 2
  image: golang:1.14.6-alpine3.11
  before_script:
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
    - *zip-prepare
  script:
    - |
      AppBuildVersion="$APP_BUILD_VERSION"
      AppBuildHash="$COMMIT_HASH"
      AppBuildDate="$BUILD_DATE"
      AppBuildMode="$APP_BUILD_MODE"
      for ARCH in $ARCHES; do
        echo "Building backend for $ARCH";
        PRINTABLE_ARCH="-$ARCH"
        if [ $ARCH = $ARCH_DEFAULT ]; then
          PRINTABLE_ARCH=
        fi
        CGO_ENABLED=0 GOOS=linux GOARCH="$ARCH" go build \
          -a \
          -installsuffix cgo \
          -ldflags "-extldflags '-static' -s -w \
          -X gitlab.com/flattrack/flattrack/src/backend/common.AppBuildVersion=$AppBuildVersion \
          -X gitlab.com/flattrack/flattrack/src/backend/common.AppBuildHash=$AppBuildHash \
          -X gitlab.com/flattrack/flattrack/src/backend/common.AppBuildDate=$AppBuildDate \
          -X gitlab.com/flattrack/flattrack/src/backend/common.AppBuildMode=$AppBuildMode" \
          -o $RELEASE_FOLDER_NAME/flattrack$PRINTABLE_ARCH \
          src/backend/main.go
      done
  artifacts:
    expire_in: 20 minutes
    paths:
      - flattrack*

build-zip-copy-extras:
  stage: build
  retry: 2
  image: alpine:3.11
  before_script:
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
    - *zip-prepare
  script:
    - cp -r migrations $RELEASE_FOLDER_NAME/migrations
    - cp -r templates $RELEASE_FOLDER_NAME/templates
  artifacts:
    paths:
      - flattrack*

build-zip:
  stage: zip
  retry: 2
  image: alpine:3.11
  dependencies:
    - build-zip-frontend
    - build-zip-backend
    - build-zip-copy-extras
  before_script:
    - *docker-build-taggable-name
    - *docker-pre-build-release-version
    - *zip-prepare
  script:
    - tar cvf $RELEASE_FOLDER_NAME.tar.gz $RELEASE_FOLDER_NAME
  artifacts:
    paths:
      - flattrack*.tar.gz

test_backend_e2e:
  stage: test
  image: golang:1.13.10-alpine3.11
  variables:
    APP_DB_HOST: postgres
    CGO_ENABLED: "0"
  services:
    - postgres:12.2-alpine
  before_script:
    - apk add git gcc
    - go get github.com/onsi/ginkgo/ginkgo
    - go get github.com/onsi/gomega/...
    - go build -o flattrack src/backend/main.go
    - ./flattrack &
  script:
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --progress test/backend/e2e
    
lint_frontend:
  stage: lint
  image: node:12.10.0-alpine
  allow_failure: true
  before_script:
    - npm i
  script:
    - npm run lint

lint_backend:
  stage: lint
  image: golang:1.13.10-alpine3.11
  allow_failure: true
  before_script:
    - apk add git gcc
    - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status src/backend/... test/backend/e2e/...

pages:
  image: python:3.8-buster
  stage: pages
  before_script:
    - pip install mkdocs-material
  script:
  - rm -r public
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
    - master

