---
builds:
  - id: flattrack
    dir: .
    main: .
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X gitlab.com/flattrack/flattrack/internal/common.AppBuildVersion={{ .Env.APP_BUILD_VERSION }}
      - -X gitlab.com/flattrack/flattrack/internal/common.AppBuildHash={{ .Env.APP_BUILD_HASH }}
      - -X gitlab.com/flattrack/flattrack/internal/common.AppBuildDate={{ .Env.APP_BUILD_DATE }}
      - -X gitlab.com/flattrack/flattrack/internal/common.AppBuildMode={{ .Env.APP_BUILD_MODE }}

defaultPlatforms:
  - linux/arm64
  - linux/arm/v6
  - linux/amd64
