[build]
  image = "flattrack/flattrack:0.16.1"

[env]
  APP_DB_DATABASE = "postgres"
  APP_DB_HOST = "flattrack-postgres.internal"
  APP_DB_PASSWORD = "postgres"
  APP_DB_USERNAME = "postgres"
  APP_HTTP_REAL_IP_HEADER = "Fly-Client-Ip"
  TZ = "Pacific/Auckland"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
