[build]
  image = "docker.io/flattrack/flattrack:latest"

[env]
  APP_DB_CONNECTION_STRING = '$DATABASE_URL'
  APP_HTTP_REAL_IP_HEADER = "Fly-Client-Ip"
  # TZ = "Pacific/Auckland"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
