#!/bin/bash -x

#
# script for initialisation with https://github.com/sharingio/pair instances
#

export TMATE_SOCKET="${TMATE_SOCKET:-/tmp/ii.default.target.iisocket}"

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    export FLATTRACK_NAMESPACE="${FLATTRACK_NAMESPACE:-flattrack-dev}"

    kubectl get ns $FLATTRACK_NAMESPACE || kubectl create ns $FLATTRACK_NAMESPACE
    kubectl label ns $FLATTRACK_NAMESPACE cert-manager-tls=sync

    /usr/local/bin/tmate-wait-for-socket.sh

    echo "Building and installing FlatTrack"
    echo "Starting Tilt"
    tmate -F -v -S $TMATE_SOCKET new-window -d -c "$PWD" -n tilt bash
    tmate -S $TMATE_SOCKET send-keys -t tilt "export DEFAULT_SUBDOMAIN_NAME=flattrack-dev && export FLATTRACK_DEV_HOSTNAME=\"\$DEFAULT_SUBDOMAIN_NAME.$SHARINGIO_PAIR_BASE_DNS_NAME\"" Enter
    tmate -S $TMATE_SOCKET send-keys -t tilt "tilt up --host 0.0.0.0 --hud" Enter

    echo "Building Backend"
    tmate -F -v -S $TMATE_SOCKET new-window -d -c "$PWD" -n backend bash
    tmate -S $TMATE_SOCKET send-keys -t backend "CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags \"-extldflags '-static' -s -w\" -o flattrack ./main.go" Enter

    echo "Building Frontend"
    tmate -F -v -S $TMATE_SOCKET new-window -d -c "$PWD/web" -n frontend bash
    tmate -S $TMATE_SOCKET send-keys -t frontend "npm i && npm run build" Enter
fi
