apiVersion: apps/v1
kind: Deployment
metadata:
  name: flattrack
  namespace: flattrack-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flattrack
  template:
    metadata:
      labels:
        app: flattrack
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: flattrack-registry
      containers:
      - name: flattrack
        image: registry.gitlab.com/flattrack/flattrack:latest
        # command:
        #   - "/bin/sleep"
        #   - "10000000"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
          - containerPort: 2112
        env:
          - name: TZ
            value: "Pacific/Auckland"
          - name: APP_DB_USERNAME
            value: postgres
          - name: APP_DB_PASSWORD
            value: postgres
          - name: APP_DB_HOST
            value: postgres
          - name: APP_DB_DATABASE
            value: flattrack
          - name: APP_MODE
            value: development
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

