apiVersion: v1
kind: Service
metadata:
  name: flattrack
  namespace: flattrack-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "2112"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: flattrack
