{{ if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flattrack.fullname" . }}
  labels:
    {{- include "flattrack.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "flattrack.selectorLabels" . | nindent 6 }}
{{- end }}
