apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flattrack.fullname" . }}
  labels:
    {{- include "flattrack.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  annotations:
{{- if .Values.annotations }}
{{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
type: Opaque
data:
  app-db-username: {{ .Values.postgres.username | b64enc | quote }}
  app-db-password: {{ .Values.postgres.password | b64enc | quote }}
  app-db-host: {{ .Values.postgres.host | b64enc | quote }}
  app-db-database: {{ .Values.postgres.database | b64enc | quote }}
  {{- if .Values.smtp.enabled }}
  app-smtp-username: {{ .Values.smtp.username | b64enc | quote }}
  app-smtp-password: {{ .Values.smtp.password | b64enc | quote }}
  app-smtp-host: {{ .Values.smtp.host | b64enc | quote }}
  app-smtp-port: {{ .Values.smtp.port | toString | b64enc | quote }}
  {{- end }}
